export const CANONICAL_ROUTES = [
  "/command",
  "/carnos",
  "/calendar",
  "/timeline",
  "/goals",
  "/world-class",
  "/career",
  "/networking",
  "/resume",
  "/interviews",
  "/learning",
  "/projects",
  "/research-stanford",
  "/research-lab",
  "/body",
  "/nutrition",
  "/supplements",
  "/sleep-energy",
  "/emotion",
  "/hair-skincare",
  "/life-admin",
  "/finance",
  "/housing",
  "/documents",
  "/creativity",
  "/grimoire",
  "/decisions",
  "/future-simulator",
  "/knowledge-vault",
  "/experiments",
  "/analytics",
  "/privacy",
  "/custom-trackers",
] as const;

export type CanonicalRoute = (typeof CANONICAL_ROUTES)[number];

export const BANNED_LEGACY_ROUTES = [
  "/command-dashboard",
  "/carnos-companion-dashboard",
  "/calendar-dashboard",
  "/timeline-dashboard",
  "/goals-dream-ladder-dashboard",
  "/world-class-path-dashboard",
  "/networking-referral-dashboard",
  "/resume-versioning-dashboard",
  "/learning-academy-dashboard",
] as const;
