import {
  assertDashboardCardContract,
  type DashboardCardContract,
  type DashboardSurface,
} from "./dashboard-layout-contract";

export const PHASE_7_DASHBOARD_CARD_REGISTRY: DashboardCardContract[] = [
  {
    id: "command-today-mission",
    surface: "command",
    region: "hero",
    title: "Today Mission",
    description: "Primary operating mission for the current day.",
    priority: "critical",
    status: "empty",
    sourceTables: ["daily_logs", "tasks", "goals"],
    emptyStateTitle: "No mission locked for today.",
    emptyStateDescription: "Create a daily log or task to anchor today.",
  },
  {
    id: "command-proof-actions",
    surface: "command",
    region: "primary",
    title: "Top Proof Actions",
    description: "Highest priority proof-producing actions.",
    priority: "critical",
    status: "empty",
    sourceTables: ["tasks", "proof_items", "goals"],
    emptyStateTitle: "No proof actions found.",
    emptyStateDescription: "Add or confirm tasks tied to proof.",
  },
  {
    id: "command-pending-updates",
    surface: "command",
    region: "right_panel",
    title: "Pending Updates",
    description: "Proposed Carnos/system updates waiting for confirmation.",
    priority: "high",
    status: "empty",
    sourceTables: ["ai_actions"],
    emptyStateTitle: "No pending updates.",
    emptyStateDescription: "Confirmed updates will appear here before execution.",
    errorStateTitle: "Pending updates unavailable.",
    errorStateDescription: "The pending update card could not read ai_actions state.",
    privacyNote: "Only confirmation-relevant action metadata should appear here.",
  },
  {
    id: "timeline-recent-events",
    surface: "timeline",
    region: "primary",
    title: "Recent Timeline",
    description: "Recent dated records across events, proof, logs, and actions.",
    priority: "high",
    status: "empty",
    sourceTables: ["events", "proof_items", "daily_logs", "audit_logs", "ai_actions"],
    emptyStateTitle: "No timeline records yet.",
    emptyStateDescription: "Logs, proof, events, and updates will build the timeline.",
  },
  {
    id: "calendar-today",
    surface: "calendar",
    region: "primary",
    title: "Today Calendar",
    description: "Dated tasks and events for the current day.",
    priority: "high",
    status: "empty",
    sourceTables: ["tasks", "events", "daily_logs"],
    emptyStateTitle: "Nothing scheduled for today.",
    emptyStateDescription: "Scheduled tasks and events will appear here.",
  },
  {
    id: "goals-active",
    surface: "goals",
    region: "primary",
    title: "Active Goals",
    description: "Goals with current reality, target reality, proof requirements, and linked actions.",
    priority: "critical",
    status: "empty",
    sourceTables: ["goals", "tasks", "proof_items"],
    emptyStateTitle: "No active goals yet.",
    emptyStateDescription: "Create or confirm a goal to start the dream-to-proof loop.",
  },
  {
    id: "proof-recent",
    surface: "proof",
    region: "primary",
    title: "Recent Proof",
    description: "Recent evidence attached to goals, tasks, and daily logs.",
    priority: "critical",
    status: "empty",
    sourceTables: ["proof_items", "goals", "tasks", "daily_logs"],
    emptyStateTitle: "No proof captured yet.",
    emptyStateDescription: "Proof items will appear after confirmed logs or manual capture.",
  },
  {
    id: "carnos-operating-panel",
    surface: "carnos",
    region: "right_panel",
    title: "Carnos Operating Panel",
    description: "Safe Carnos-side dashboard context, pending updates, and next action visibility.",
    priority: "high",
    status: "empty",
    sourceTables: ["chat_sessions", "chat_messages", "ai_actions"],
    emptyStateTitle: "No Carnos operating context yet.",
    emptyStateDescription: "Chat and proposed actions will appear here as the system develops.",
    errorStateTitle: "Carnos operating context unavailable.",
    errorStateDescription: "The Carnos panel could not read its source tables.",
    privacyNote: "Carnos context must remain visibility-only until later privacy and memory phases.",
  },
  {
    id: "career-application-pipeline",
    surface: "career",
    region: "primary",
    title: "Application pipeline",
    description: "Tracks job applications, active opportunities, status movement, and follow-up pressure.",
    priority: "critical",
    status: "ready",
    sourceTables: ["job_applications", "job_application_events"],
    emptyStateTitle: "No job applications found.",
    emptyStateDescription: "Applications will appear here after the Career System has application records.",
  },
  {
    id: "career-interview-readiness",
    surface: "career",
    region: "secondary",
    title: "Interview readiness",
    description: "Surfaces upcoming interviews and preparation pressure without executing any actions.",
    priority: "high",
    status: "ready",
    sourceTables: ["interviews", "tasks", "proof_items"],
    emptyStateTitle: "No interviews found.",
    emptyStateDescription: "Interview rounds will appear here after interview records exist.",
  },
  {
    id: "networking-referral-pipeline",
    surface: "networking",
    region: "primary",
    title: "Networking and referral pipeline",
    description: "Tracks contacts, interactions, referral status, and follow-up timing.",
    priority: "high",
    status: "ready",
    sourceTables: ["networking_contacts", "networking_interactions", "job_referrals"],
    emptyStateTitle: "No networking contacts found.",
    emptyStateDescription: "Contacts and referral activity will appear here after networking records exist.",
  },
  {
    id: "resume-version-control",
    surface: "resume",
    region: "primary",
    title: "Resume version control",
    description: "Tracks resume versions, target roles, target companies, keywords, and evidence-linked bullets.",
    priority: "high",
    status: "ready",
    sourceTables: ["resume_versions", "resume_bullets", "proof_items"],
    emptyStateTitle: "No resume versions found.",
    emptyStateDescription: "Resume versions will appear here after resume records exist.",
  },
  {
    id: "interview-command-center",
    surface: "interviews",
    region: "primary",
    title: "Interview command center",
    description: "Tracks interview rounds, prep notes, outcomes, and follow-up needs.",
    priority: "high",
    status: "ready",
    sourceTables: ["interviews", "job_applications", "tasks"],
    emptyStateTitle: "No interview rounds found.",
    emptyStateDescription: "Interview rounds will appear here after interview records exist.",
  },

  {
    id: "learning-skill-paths",
    surface: "learning",
    region: "primary",
    title: "Skill path command",
    description: "Tracks active skill paths, learning priorities, mastery targets, and proof requirements.",
    priority: "critical",
    status: "ready",
    sourceTables: ["skill_paths", "skills", "skill_progress", "learning_sessions"],
    emptyStateTitle: "No skill paths found.",
    emptyStateDescription: "Skill paths will appear after learning records exist.",
  },
  {
    id: "learning-practice-loop",
    surface: "learning",
    region: "secondary",
    title: "Practice and quiz loop",
    description: "Surfaces study sessions, quiz attempts, weak points, and next review pressure.",
    priority: "high",
    status: "ready",
    sourceTables: ["learning_sessions", "quizzes", "quiz_attempts", "skills"],
    emptyStateTitle: "No learning sessions or quizzes found.",
    emptyStateDescription: "Practice sessions and quiz attempts will appear after learning activity is recorded.",
  },
  {
    id: "projects-shipping-pipeline",
    surface: "projects",
    region: "primary",
    title: "Project shipping pipeline",
    description: "Tracks portfolio projects, milestones, releases, proof, and shipping state.",
    priority: "critical",
    status: "ready",
    sourceTables: ["projects", "project_milestones", "project_releases", "proof_items"],
    emptyStateTitle: "No projects found.",
    emptyStateDescription: "Projects will appear after project records exist.",
  },
  {
    id: "projects-quality-loop",
    surface: "projects",
    region: "secondary",
    title: "Quality and evidence loop",
    description: "Tracks bugs, tests, links, demos, and evidence needed to make projects trustworthy.",
    priority: "high",
    status: "ready",
    sourceTables: ["project_bugs", "project_tests", "project_links", "proof_items"],
    emptyStateTitle: "No project quality records found.",
    emptyStateDescription: "Bugs, tests, links, and release evidence will appear after project records exist.",
  },
  {
    id: "research-lab-idea-pipeline",
    surface: "research_lab",
    region: "primary",
    title: "Research idea pipeline",
    description: "Tracks research ideas, questions, claims, experiments, and proof-backed paper readiness.",
    priority: "critical",
    status: "ready",
    sourceTables: [
      "research_ideas",
      "research_questions",
      "research_claims",
      "research_experiments",
      "research_results",
      "research_papers",
    ],
    emptyStateTitle: "No research ideas found.",
    emptyStateDescription: "Research ideas will appear after Phase 10 records exist.",
    privacyNote: "Research surfaces are read-only until proposed-action workflows are explicitly wired.",
  },
  {
    id: "research-lab-literature-citations",
    surface: "research_lab",
    region: "secondary",
    title: "Literature and citation tracker",
    description: "Surfaces saved literature, citation purpose, paper linkage, and evidence pressure.",
    priority: "high",
    status: "ready",
    sourceTables: ["research_literature_items", "research_citations", "research_claims"],
    emptyStateTitle: "No literature records found.",
    emptyStateDescription: "Literature and citations will appear after reading records exist.",
  },
  {
    id: "research-stanford-target-fit",
    surface: "research_stanford",
    region: "primary",
    title: "Stanford and PhD target fit",
    description: "Tracks target universities, labs, professors, fit reasons, and outreach readiness.",
    priority: "critical",
    status: "ready",
    sourceTables: ["target_universities", "target_labs", "target_professors"],
    emptyStateTitle: "No PhD targets found.",
    emptyStateDescription: "Universities, labs, and professors will appear after target records exist.",
    privacyNote: "No automatic outreach or scraping is enabled in Phase 10.",
  },
  {
    id: "research-stanford-application-readiness",
    surface: "research_stanford",
    region: "secondary",
    title: "PhD application readiness",
    description: "Tracks readiness assessments, SOP versions, application assets, and recommendation targets.",
    priority: "high",
    status: "ready",
    sourceTables: [
      "phd_readiness_assessments",
      "phd_application_assets",
      "sop_versions",
      "recommendation_targets",
    ],
    emptyStateTitle: "No PhD readiness records found.",
    emptyStateDescription: "Readiness, SOP, assets, and recommendation records will appear after records exist.",
  },
  {
    id: "grimoire-mode-selector",
    surface: "grimoire",
    region: "primary",
    title: "Mode Selector",
    description: "Shows available symbolic modes, mission type, intensity, active state, and reversion requirement without activating anything.",
    priority: "critical",
    status: "ready",
    sourceTables: ["grimoire_modes"],
    emptyStateTitle: "No Grimoire modes found.",
    emptyStateDescription: "Define a mode only after mission type, allowed use, proof requirement, corruption risk, and reversion rule are clear.",
    privacyNote: "Modes remain private to the authenticated user and cannot activate from the read-only dashboard.",
  },
  {
    id: "grimoire-mission-mapping",
    surface: "grimoire",
    region: "primary",
    title: "Mission Mapping",
    description: "Shows mode-to-mission logs, active mission statements, proof/action mapping, and reversion pressure without creating records.",
    priority: "critical",
    status: "ready",
    sourceTables: ["grimoire_daily_logs", "grimoire_modes", "proof_items"],
    emptyStateTitle: "No Grimoire mission mappings found.",
    emptyStateDescription: "A symbolic mode should not be treated as active until it maps to one practical mission and one proof-producing action.",
    privacyNote: "Mission mappings are read-only and must not become proposed actions until a later safe confirmation flow exists.",
  },
];

export function getDashboardCardsForSurface(surface: DashboardSurface): DashboardCardContract[] {
  return PHASE_7_DASHBOARD_CARD_REGISTRY
    .filter((card) => card.surface === surface)
    .map(assertDashboardCardContract);
}

export function getDashboardCardById(cardId: string): DashboardCardContract | null {
  const card = PHASE_7_DASHBOARD_CARD_REGISTRY.find((item) => item.id === cardId);
  return card ? assertDashboardCardContract(card) : null;
}

export function assertDashboardCardRegistry(): DashboardCardContract[] {
  const seen = new Set<string>();

  return PHASE_7_DASHBOARD_CARD_REGISTRY.map((card) => {
    if (seen.has(card.id)) {
      throw new Error(`Duplicate dashboard card id: ${card.id}`);
    }

    seen.add(card.id);
    return assertDashboardCardContract(card);
  });
}
